on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 24.x
      - name: Run tests
        run: ./run-tests.sh
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: junit-report
          path: test-results/junit.xml